config/routes.rb
Tester4::Application.routes.draw do
  
  devise_for :users
  
  authenticated do
    root :to => 'pages#panel', as: :authenticated_user
  end
  root 'pages#index'
  
  resources :pages
  resources :posts
  resources :videos
  

  

end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/video.rb
class Video < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < ApplicationController
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index   
  end
  
  def panel   
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  before_action :authenticate_user!, only: [:new, :create]
  
  def index
    @posts = Post.all
  end
  
  def new
    @post = Post.new
  end
  
  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to posts_path
    end
  end
  
  private
  
  def post_params
    params.require(:post).permit(:title)
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  def index
    @videos = Video.all
  end
  
  def new
    @video = Video.new
  end
  
  def create
    @video = Video.new(video_params)
    if @video.save
      redirect_to videos_path
    else
      render 'new'
    end
  end
  
  def edit
  end
  
  def update
    if @video.update(video_params)
      redirect_to videos_path
    else
      render 'edit' 
    end
  end
  
  def destroy
    @video.destroy
  end
  
  private
  
  def video_params
    params.require(:video).permit(:title,:length, :calories, :url)
  end
  
  
  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/omniauth_callbacks_helper.rb
module OmniauthCallbacksHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tester4</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
	<div class="navbar">
		<div class="navbar-inner">
			<a href="#" class="brand"> <img src="/images/gymoline_logo_nav.png"> </a>
			<ul class="nav pull-right">
				<li class="active"><a href="#">Nosotros</a></li>
				<li><a href="#">Contactanos</a></li>
				
				<% if user_signed_in? %>
					<li><%= link_to "Editar", edit_user_registration_path %></li>
					<li><%= link_to "Cerrar Sesion", destroy_user_session_path, method: :delete %></li>
				<% else %>
					<li><a href=<%=new_user_session_path %>><button class="btn" type="button">Ingresa</button></a></li>
					<li><a href=<%=new_user_registration_path %>><button class="btn" type="button">Registrate</button></a></li>
				<% end %>
					
			</ul>
		</div>	
	</div>	
	
	<div class="container">	
		<%= yield %>
	</div>

</body>
</html>

app/views/pages/index.html.erb
<div class="hero-unit">
	<div class="row">
		<img src="/images/hero-wide-opt.jpg"> 
	</div>
</div>
<div class ="row">
	<div class="span4"> 
		<h2><img src="/images/bs-docs-bootstrap-features.png"></h2> 
		<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut sit amet scelerisque tortor. Fusce lobortis ut leo ac viverra. 
			Suspendisse hendrerit risus libero</p> 
	</div>
	<div class="span4"> 
		<h2><img src="/images/bs-docs-responsive-illustrations.png"></h2> 
		<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut sit amet scelerisque tortor. Fusce lobortis ut leo ac viverra. 
			Suspendisse hendrerit risus libero</p> 
	</div>
	<div class="span4"> 
		<h2><img src="/images/bs-docs-bootstrap-features.png"></h2> 
		<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut sit amet scelerisque tortor. Fusce lobortis ut leo ac viverra. 
			Suspendisse hendrerit risus libero</p> 
	</div>
</div>

app/views/pages/panel.html.erb
<h1> Bienvenido <%= current_user.email %></h1>

<div class="row">
	<div class="span4">
		<h2>Nueva Rutina</h2>
		<p>Empieza con tu rutina de ejercicios ya!</p>
	</div>
	<div class="span4">
		<h2>Tiempo ejercitado</h2>
	</div>
	<div class="span4">
		<h2>Calorias Quemadas</h2>
	</div>
</div>

app/views/posts/index.html.erb
<h1>Tus posts </h1>

<% @posts.each do |post| %>
	<p><%= post.title %></p>
<% end %>

<%= link_to "nuevo post", new_post_path %>

app/views/posts/new.html.erb
<h1>Primer post</h1>

<%= form_for @post do |f| %>
	<%= f.label :title %>
	<%= f.text_field :title %>
	<%= f.submit %>
<% end %>

app/views/videos/index.html.erb
<h2>Esta es la lista de videos </h2>

<table>
	<tr>
		<th>Titulo</th>
		<th>Duracion</th>
		<th>Calorias</th>
		<th>Url</th>
	</tr>
<% @videos.each do |video| %>
	
	<tr>
		<td><%= video.title %></td>
		<td><%= video.length %></td>
		<td><%= video.calories %></td>
		<td><%= video.url.html_safe %></td>
		<td><%= link_to "Editar", edit_video_path(video) %></td>
		<td><%= link_to "Borrar", video, method: :delete, data: {confirm: 'Estas seguro?'} %></td>
	</tr>
<% end %>
</table>
	<p><%= link_to "Nuevo video", new_video_path %></p>

app/views/videos/new.html.erb
<%= form_for @video do |f| %>
	<p>
		<%= f.label :titulo %>
		<%= f.text_field :title %>
	</p>
	<p>
		<%= f.label :duracion %>
		<%= f.text_field :length %>
	</p>
	<p>
		<%= f.label :calorias %>
		<%= f.text_field :calories %>
	</p>
	<p>
		<%= f.label :url %>
		<%= f.text_field :url %>
	</p>
	<%= f.submit %>
<% end %>